# Generated by Django 6.0.3 on 2026-03-07 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brush_track_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('progress_percentage', models.IntegerField()),
                ('message', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brush_track_app.work')),
            ],
        ),
    ]
