# Generated by Django 6.0.3 on 2026-03-07 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brush_track_app', '0002_workstatusupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
