# Generated by Django 6.0.3 on 2026-03-06 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brush_track_app', '0002_notification_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brush_track_app.client')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brush_track_app.supervisor')),
            ],
        ),
    ]
