# Generated by Django 6.0.3 on 2026-03-07 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brush_track_app', '0003_delete_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='workassign',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brush_track_app.client'),
            preserve_default=False,
        ),
    ]
