# Generated by Django 6.0.3 on 2026-03-07 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brush_track_app', '0003_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brush_track_app.client')),
                ('work_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brush_track_app.work')),
            ],
        ),
    ]
