# Generated by Django 6.0.3 on 2026-03-07 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brush_track_app', '0004_issue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='client',
            new_name='complaint_details',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='description',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='work_request',
        ),
        migrations.AddField(
            model_name='issue',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='subject',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
