# Generated by Django 6.0.3 on 2026-03-08 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brush_track_app', '0004_workassign_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkAssign',
        ),
    ]
