# Generated by Django 6.0.3 on 2026-03-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brush_track_app', '0005_rename_client_issue_complaint_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_complaint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
