# Generated by Django 6.0.3 on 2026-03-08 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brush_track_app', '0005_delete_workassign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstatusupdate',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='brush_track_app.work'),
        ),
        migrations.CreateModel(
            name='WorkAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('painting', 'Painting'), ('washing', 'Washing'), ('cleaning', 'Cleaning')], max_length=20)),
                ('area', models.CharField(choices=[('hall', 'Hall'), ('bedroom', 'Bedroom'), ('kitchen', 'Kitchen'), ('bathroom', 'Bathroom'), ('exterior', 'Exterior')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brush_track_app.client')),
                ('painter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brush_track_app.painter')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brush_track_app.supervisor')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brush_track_app.work')),
            ],
        ),
    ]
