# Generated by Django 6.0.3 on 2026-03-08 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brush_track_app', '0006_alter_workstatusupdate_work_workassign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('painter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brush_track_app.painter')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brush_track_app.work')),
            ],
        ),
    ]
