# Generated by Django 6.0.3 on 2026-03-07 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brush_track_app', '0006_notification_is_complaint_notification_replied_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_complaint',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='replied_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='reply',
        ),
    ]
