# Generated by Django 6.0.3 on 2026-03-07 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brush_track_app', '0007_remove_notification_is_complaint_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Issue',
            new_name='Complaint',
        ),
    ]
