# Generated by Django 6.0.3 on 2026-03-07 06:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brush_track_app', '0008_rename_issue_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='supervisor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brush_track_app.supervisor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
