from django.urls import path

from brush_track_app import views, clientview, superview, painterview, adminview

urlpatterns = [
path('',views.index,name='index'),
path('login_page',views.login_page,name='login_page'),
path('login_view',views.login_view,name='login_view'),
path('admin',views.admin,name='admin'),
path('client',views.client,name='client'),
path('supervisor',views.supervisor,name='supervisor'),
path('painters',views.painters,name='painters'),
path('client_add',views.client_add,name='client_add'),
path('client_profile',clientview.client_profile,name='client_profile'),
path('supervisor_add',views.supervisor_add,name ='supervisor_add'),
path('supervisor_profile',superview.supervisor_profile,name='supervisor_profile'),
path('painter_add',views.painter_add,name='painter_add'),
path('painter_profile',painterview.painter_profile,name='painter_profile'),
path('supervisor_view',clientview.supervisor_view,name='supervisor_view'),
path('painters_view',superview.painters_view,name='painters_view'),
path('notification',superview.notification,name='notification'),
path('send_notification',superview.send_notification,name='send_notification'),
    path('painter_notifications',painterview.painter_notifications,name='painter_notifications'),
path('send_request/<int:id>/', clientview.send_request, name='send_request'),
path('my_works',clientview.my_works,name='my_works'),
path('supervisor_requests/', superview.supervisor_requests, name='supervisor_requests'),

path('accept_request/<int:id>/', superview.accept_request, name='accept_request'),
path('painter-assigned-works/', painterview.painter_assigned_works, name='painter_assigned_works') ,
    path('reject_request/<int:id>/', superview.reject_request, name='reject_request'),
path('client_requests',clientview.client_requests,name='client_requests'),
path("add_work/<int:id>/", clientview.add_work, name="add_work"),
path('accept_work/<int:id>/', superview.accept_work, name="accept_work"),
path('reject_work/<int:id>/', superview.reject_work, name="reject_work"),
path('client_notifications/',clientview.client_notifications,name="client_notifications"),
path("add_rating/<int:id>/",clientview.add_rating,name="add_rating"),
path('supervisor_works/', superview.supervisor_works, name='supervisor_works'),
path('add_work_status_update/<int:id>/', superview.add_work_status_update, name='add_work_status_update'),
path('assign-painter/<int:id>/', superview.assign_painter, name='assign-painter'),
path('assigned-works/', superview.supervisor_assigned_works, name='assigned_works'),
path('work-status/<int:id>/', clientview.work_status, name='work_status'),
path('Log_out_client',clientview.Log_out_client,name='Log_out_client'),
    path('client_dashboard',clientview.client_dashboard,name='client_dashboard'),
path('client_view',adminview.client_view,name='client_view'),
path('supervisors_view',adminview.supervisors_view,name='supervisors_view'),
path('client_delete/<int:id>/',adminview.client_delete,name='client_delete'),
path('super_delete/<int:id>/',adminview.super_delete,name='super_delete'),
path('supervisor_dashboard',superview.supervisor_dashboard,name='supervisor_dashboard'),
path('super_update/<int:id>/', superview.super_update, name='super_update'),
path('supervisor/send_message/<int:client_id>/',superview.send_message_to_client, name='send_message_to_client'),
    path('client/messages/', clientview.client_messages, name='client_messages'),
path('client_update/<int:id>/',clientview.client_update,name='client_update'),
path('Log_out_painter',painterview.Log_out_painter,name='Log_out_painter'),
path('Log_out_super',superview.Log_out_super,name='Log_out_super'),


]

